<a href="https://colab.research.google.com/github/cassidysimmons/deep-learning-challenge/blob/main/AlphabetSoupCharity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T2', 'T17', 'T15', 'T29', 'T14', 'T25', 'T12', 'T13', 'T9']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts() > 1

CLASSIFICATION
C1000     True
C2000     True
C1200     True
C3000     True
C2100     True
         ...
C4120    False
C8210    False
C2561    False
C4500    False
C2150    False
Name: count, Length: 71, dtype: bool

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ['C2700', 'C7000', 'C7200',
       'C1700', 'C4000', 'C7100', 'C2800', 'C6000', 'C1238',
       'C5000', 'C7120', 'C1800', 'C4100', 'C1400', 'C1270', 'C2300',
       'C8200', 'C1500', 'C7210', 'C1300', 'C1230', 'C1280', 'C1240',
       'C2710', 'C2561', 'C1250', 'C8000', 'C1245', 'C1260', 'C1235',
       'C1720', 'C1257', 'C4500', 'C2400', 'C8210', 'C1600', 'C1278',
       'C1237', 'C4120', 'C2170', 'C1728', 'C1732', 'C2380', 'C1283',
       'C1570', 'C2500', 'C1267', 'C3700', 'C1580', 'C2570', 'C1256',
       'C1236', 'C1234', 'C1246', 'C2190', 'C4200', 'C0', 'C3200',
       'C5200', 'C1370', 'C2600', 'C1248', 'C6100', 'C1820', 'C1900',
       'C2150']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`

# encoding the non-numeric data
dummies = pd.get_dummies(data= application_df)

# combining the newly encoded data with the original dataframe
concat_df = pd.concat([application_df, dummies], axis=1)

# removing duplicate columns
concat_df = concat_df.loc[:,~concat_df.columns.duplicated()].copy()

# dropping the old, not encoded columns
concat_df = concat_df.drop(columns=['AFFILIATION','APPLICATION_TYPE', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'SPECIAL_CONSIDERATIONS', 'INCOME_AMT'])

concat_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
y = concat_df['IS_SUCCESSFUL']
X = concat_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation="relu", input_dim=43))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 220

 dense_1 (Dense)             (None, 5)                 30

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 256 (1.00 KB)
Trainable params: 256 (1.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.6013 - accuracy: 0.6964
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5680 - accuracy: 0.7239
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5624 - accuracy: 0.7244
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5592 - accuracy: 0.7268
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7264
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5562 - accuracy: 0.7276
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5557 - accuracy: 0.7272
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5549 - accuracy: 0.7276
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5540 - accuracy: 0.7279
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7275
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7272
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7272
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7277
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5532 - accuracy: 0.7272
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7280
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7290
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5521 - accuracy: 0.7276
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7298
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7290
Epoch 20/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5522 - accuracy: 0.7285
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7282
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7270
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7277
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7290
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7288
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5513 - accuracy: 0.7291
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5515 - accuracy: 0.7289
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7288
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7288
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7280
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7288
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7290
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7288
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7295
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7289
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7289
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7297
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7294
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7296
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7297
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7298
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7297
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7297
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7291
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7297
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7294
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5494 - accuracy: 0.7309
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5494 - accuracy: 0.7306
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7302
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7302
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7298
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7298
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7299
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7310
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7300
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7303
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7299
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7307
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7312
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7308
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7318
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7314
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7307
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7311
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7303
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7304
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7315
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7318
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7310
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7313
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7312
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7315
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7311
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7311
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7311
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7321
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7317
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5484 - accuracy: 0.7320
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7317
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7322
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5485 - accuracy: 0.7315
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7315
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7305
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7301
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7315
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7311
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7314
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7314
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7310
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7320
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7322
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7315
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7310
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7308
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7311
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7325
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7319
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7317
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7318
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7313

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5559 - accuracy: 0.7271 - 519ms/epoch - 2ms/step
Loss: 0.555885910987854, Accuracy: 0.7271137237548828

In [17]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(